#!/bin/zsh

if [[ "$(arch)" == "i386" ]]; then
	mv TempPackage/tempMac .
	mv tempMac temp
elif [[ "$(arch)" == "aarch64" ]]; then
	mv TempPackage/tempArm .
	mv tempArm temp
else
	mv TempPackage/tempX86_64 .
	mv tempX86_64 temp
fi
